FROM node:24.15.0-alpine

RUN npm install -g pnpm@10.33.2

WORKDIR /app

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* .npmrc* ./

RUN pnpm install

COPY . .

RUN pnpm exec prisma generate

EXPOSE 8080

CMD ["sh", "-c", "pnpm exec prisma generate && pnpm start:dev"]
