FROM node:24.15.0-alpine

RUN npm install -g pnpm@10.33.2

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

RUN pnpm prisma:generate

EXPOSE 8080

CMD ["pnpm", "start:dev"]
